"use client";

import { Target, ArrowRight } from "@phosphor-icons/react";
import type { ViewModel } from "@/lib/adapter";
import { DashHead, Panel, MetricTile } from "./shared";
import { ScoreDial, Meter } from "@/components/charts";
import { Badge, EmptyState } from "@/components/primitives";
import { tone as toneMap, toneOfScore } from "@/lib/format";
import { formatGeoScore } from "@/lib/geoRating";

export default function OverviewSection({ vm, onNavigate }: { vm: ViewModel; onNavigate?: (id: string) => void }) {
  const quickWins = vm.actions.list.slice(0, 4);

  return (
    <>
      <DashHead
        title={`${vm.brand} — GEO overview`}
        lede={
          vm.generatedAt
            ? `${vm.domain} · audited ${vm.generatedAt}. ${vm.headline}`
            : `${vm.domain}. ${vm.headline}`
        }
      />

      <div className="grid gap-4 lg:grid-cols-[minmax(0,300px)_1fr]">
        <Panel className="flex flex-col items-center justify-center gap-3 text-center">
          <ScoreDial
            value={vm.score.overallExact}
            size={200}
            label="Overall GEO Rating"
            displayValue={vm.score.presentation}
            secondaryText={vm.score.numericAvailable ? `Score ${formatGeoScore(vm.score.overallExact)}` : "Limited data"}
            active={vm.score.has}
          />
          <p className="text-2xs uppercase tracking-[0.08em] text-ink-3">Overall GEO Rating</p>
          {vm.score.dataConfidence === "Limited" && <p className="text-xs text-ink-3">Data confidence: Limited</p>}
        </Panel>

        <Panel title="Executive summary">
          {vm.report.hasExecutive ? (
            <>
              <p className="text-sm leading-relaxed text-ink-2">
                {vm.report.executiveMarkdown.replace(/[#*_>`-]/g, "").split("\n").filter(Boolean).slice(0, 4).join(" ")}
              </p>
              <button
                type="button"
                onClick={() => onNavigate?.("report")}
                className="mt-3 inline-flex items-center gap-1 text-2xs font-semibold text-brand-dark hover:underline"
              >
                Read the full report <ArrowRight size={12} weight="bold" />
              </button>
            </>
          ) : vm.headline ? (
            <p className="text-sm leading-relaxed text-ink-2">{vm.headline}</p>
          ) : (
            <EmptyState title="No summary provided">The executive report is generated by the audit backend.</EmptyState>
          )}
        </Panel>
      </div>

      {vm.headlineMetrics.length > 0 && (
        <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {vm.headlineMetrics.map((m) => (
            <MetricTile key={m.label} label={m.label} value={m.value} sub={m.sub} tone={m.tone} />
          ))}
        </div>
      )}

      <Panel
        title="Dimension scores"
        className="mt-4"
        action={
          <button type="button" onClick={() => onNavigate?.("ai-visibility")} className="text-2xs font-semibold text-brand-dark hover:underline">
            Dig in
          </button>
        }
      >
        {vm.hasDimensions ? (
          <ul className="grid gap-x-8 gap-y-3 sm:grid-cols-2">
            {vm.dimensions.map((d) => (
              <li key={d.key} className="grid grid-cols-[9rem_1fr_2.5rem] items-center gap-3">
                <span className="truncate text-sm text-ink-2" title={d.label}>
                  {d.label}
                </span>
                <Meter value={d.score} />
                <span className={`data-fig text-right text-sm ${toneMap[toneOfScore(d.score)].text}`}>{d.score}</span>
              </li>
            ))}
          </ul>
        ) : (
          <EmptyState title="No dimension breakdown">
            The backend&apos;s <code className="rounded bg-subtle px-1 py-0.5 text-2xs">geo_score.score_components</code> was empty for this audit.
          </EmptyState>
        )}
      </Panel>

      <div className="mt-4 grid gap-4">
        <Panel
          title="Do these first"
          action={
            <button type="button" onClick={() => onNavigate?.("actions")} className="text-2xs font-semibold text-brand-dark hover:underline">
              Action Center
            </button>
          }
        >
          {quickWins.length > 0 ? (
            <ol className="divide-y divide-line">
              {quickWins.map((a) => (
                <li key={a.id} className="flex items-start gap-3 py-3 first:pt-0 last:pb-0">
                  <span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-subtle text-2xs font-bold text-ink-2">
                    {String(a.id).padStart(2, "0")}
                  </span>
                  <div>
                    <p className="text-sm font-semibold text-ink">{a.title}</p>
                    <p className="mt-0.5 text-2xs uppercase tracking-[0.05em] text-ink-3">
                      {a.dimension} · impact {a.impact}/5 · effort {a.effort}/5
                    </p>
                  </div>
                  <Badge tone={a.type === "Quick win" ? "pos" : "neutral"} className="ml-auto shrink-0">
                    {a.type}
                  </Badge>
                </li>
              ))}
            </ol>
          ) : (
            <EmptyState title="No open findings">
              This audit returned no gaps in <code className="rounded bg-subtle px-1 py-0.5 text-2xs">gap_report.gaps</code>.
            </EmptyState>
          )}
        </Panel>
      </div>

      {vm.competitors.has && (
        <div className="mt-4 rounded-xl border border-brand/30 bg-brand-soft/50 p-5">
          <div className="flex items-start gap-3">
            <Target size={20} weight="bold" className="mt-0.5 shrink-0 text-brand-dark" />
            <div>
              <p className="text-sm font-bold text-ink">
                {vm.competitors.brandShareOfVoice == null
                  ? "Share of voice not measured"
                  : `${vm.competitors.brandShareOfVoice.toFixed(1)}% share of voice`} · {vm.competitors.list.length} tracked competitors
              </p>
              <p className="mt-1 text-sm text-ink-2">
                Closing the share-of-voice gap is the single biggest lever on your GEO score.
              </p>
              <button
                type="button"
                onClick={() => onNavigate?.("competitors")}
                className="mt-2 inline-flex items-center gap-1 text-2xs font-semibold text-brand-dark hover:underline"
              >
                Open competitor intelligence <ArrowRight size={12} weight="bold" />
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
